ALTER TABLE personas ADD COLUMN password VARCHAR(255) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS notas (
    idNota INT AUTO_INCREMENT PRIMARY KEY,
    idPersona INT NOT NULL,
    mensaje TEXT NOT NULL,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (idPersona) REFERENCES personas(idPersona) ON DELETE CASCADE
);
